version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - 5432

  rabbitmq:
    container_name: broker
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672

  api:
    container_name: api
    image: api
    build:
      context: .
      dockerfile: ./Api.Dockerfile
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@postgres?sslmode=disable
      - RABBIT_MQ_URL=amqp://guest:guest@rabbitmq
    ports:
      - "8088:8088"
    restart: on-failure
    depends_on:
      - postgres
      - rabbitmq
      - worker

  worker:
    container_name: worker
    image: worker
    restart: on-failure
    build:
      context: .
      dockerfile: ./Worker.Dockerfile
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@postgres?sslmode=disable
      - RABBIT_MQ_URL=amqp://guest:guest@rabbitmq
    depends_on:
      - postgres
      - rabbitmq


#  migration:
#    image: api:latest
#    command: [ "migration-script.sh" ]
#    links:
#      - postgres
#    depends_on:
#      - postgres